index/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    path('account/<slug:user>', views.userAccount, name="userAccount"),
    path('account/<slug:user>/password_forgot', views.forgotPassword, name="forgotPassword"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('store/', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'store'

urlpatterns = [
    path('test/', views.test, name="test"),
    path('', views.index, name="index"),
    path('cart/', views.cart, name="cart"),
    path('<slug:orderid>/ordercancel/', views.ordercancel, name="ordercancel"),
    path('checkout/', views.checkout, name="checkout"),
    path('addtocart/<item>/', views.addtocart, name="addtocart"),
    path('trackorderred/', views.trackorderred, name="trackorderred"),
    path('trackorder/', views.track_order, name="track_order"),
    path('trackorder/<slug:order_track>', views.trackorder, name="trackorder"),
    path('apply_coupon/', views.apply_coupon, name="apply_coupon"),
    path('remove_coupon/', views.remove_coupon, name="remove_coupon"),
    path('add_product/', views.addProduct, name="addProduct"),
    path('rate_product/', views.rate_product, name="rate_product"),
    path('product/<int:product_id>', views.viewProduct, name="viewProduct"),
    path('api/products', views.productsApi, name='productApi'), 
    path('api/', views.api, name='api'), 
    path('api/products/<str:pk>', views.singleProductApi, name='singleProductApi'), 
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.deletion import DO_NOTHING, SET_DEFAULT, SET_NULL
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Customer(models.Model):
    def __str__(self):
        if self.name:
            return str(self.name)
        else:
            return str(self.uid)

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    uid = models.CharField(max_length=500, null=True, blank=True)


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)


class Product(models.Model):
    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    seller = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)

    title = models.CharField(max_length=200, null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    info = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    in_stock = models.BooleanField(default=True)
    qty = models.IntegerField(null=True, blank=True)
    price = models.FloatField(default=1)
    image = models.ImageField(upload_to='images/')
    ratings = models.FloatField(null=True, blank=True)
    avg_ratings = models.FloatField(null=True, blank=True)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Rating(models.Model):
    rating = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)], null=True, blank=True)
    product_rated = models.ForeignKey(Product, on_delete=SET_NULL, null=True, blank=True)
    customer_rated = models.ForeignKey(Customer, on_delete=DO_NOTHING, null=True, blank=True)



class ShippingAddress(models.Model):
    def __str__(self):
        return self.address

    address = models.CharField(max_length=200)
    address2 = models.TextField(max_length=500)
    city = models.CharField(max_length=200)
    state = models.CharField(max_length=200)


class Coupon(models.Model):
    def __str__(self):
        return self.coupon

    coupon = models.CharField(max_length=50)
    value = models.FloatField()


class Order(models.Model):
    def __str__(self):
        return str(self.id)

    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True, blank=True)

    address = models.ForeignKey(
        ShippingAddress, on_delete=models.SET_NULL, blank=True, null=True)

    coupon = models.ForeignKey(
        Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    coupon_activated = models.BooleanField(
        default=False, null=True, blank=False)
    date_ordered = models.DateTimeField(auto_now_add=True)
    total = models.FloatField(null=True, blank=True)
    totalAfterCoupon = models.FloatField(null=True, blank=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)
    shipped = models.BooleanField(default=False, null=True, blank=False)
    deliveryDate = models.DateField(null=True, blank=True)


class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, null=True, blank=True)
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(
        default=1,  validators=[MinValueValidator(1), MaxValueValidator(100)])

    @property
    def getTotal(self):
        return self.product.price * self.quantity


def create_customer(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(
            user=instance, name=instance.username, email=instance.email)


post_save.connect(create_customer, sender=User)


def update_customer(sender, instance, created, **kwargs):
    if created == False:
        print(instance)
        Customer.objects.select_for_update().filter(user=instance).update(
            user=instance, name=instance.username, email=instance.email)


post_save.connect(update_customer, sender=User)

store/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from rest_framework import serializers
from .models import Product, Category, Customer, ShippingAddress, Order, OrderItem, Coupon, User, Rating
from django.contrib.auth.models import Group
from django.http import HttpResponse, JsonResponse, Http404, HttpResponseRedirect, response
from django.core.paginator import Paginator
from django.contrib import messages
from random import *
from .forms import CreateShippingAddress, NewProduct
from django.utils.safestring import mark_safe
import time, re
import uuid
import datetime
from datetime import timedelta
from .serializers import ProductSerializer
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.authtoken.models import Token
# Create your views here.

#// TODO user generated reviews
# TODO wishlist
# TODO realted items
# TODO Special offers
#* -------------------
# TODO and add them in the filter option

def index(request):
    cat = request.GET.get('cat')
    categor = None
    product_search = None

    Product.objects.select_for_update().filter(in_stock=True, qty = 0).update(in_stock=False)

    products = Product.objects.all()

    if(request.GET.get('price') == 'lowest'):
        products = Product.objects.order_by('price')

    elif(request.GET.get('price') == 'highest'):
        products = Product.objects.order_by('-price')

    if(request.GET.get('clear') != None):
        return redirect('store:index')

    if(request.GET.get('product_search')):
        if(len(request.GET.get('product_search')) != 0):
            product_search = request.GET.get('product_search')
            product = Product.objects.filter(title__contains=product_search)
            products = product

    # TODO adding pagination to products
    # paginator = Paginator(products, 2)

    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)

    try:
        categor = Category.objects.get(id=cat)
    except:
        pass

    if request.user.is_authenticated:
        customer = get_object_or_404(Customer, user=request.user)
    else:
        uid = request.COOKIES.get('device')
        print('i', uid)
        try:
            customer = Customer.objects.get(uid=uid)
            print(customer)
        except:
            customer = Customer(uid=uid)
            if str(customer) == 'None':
                pass
            else:
                customer.save()

    orderItems = None

    try:
        order = Order.objects.get(customer=customer, complete=False)
        orderItems = OrderItem.objects.filter(order=order)
    except:
        pass

    categories = Category.objects.all()
    if len(products) == 0:
        messages.warning(
            request, 'No products found! Clear your filters and try again')

    ctx = {'orderItems': orderItems, 'products': products, 'categories': categories,
           'cat': cat, 'categor': categor, 'ps': product_search}
    return render(request, 'store/store.html', ctx)


def cart(request):
    data = {}
    if request.user.is_authenticated:
        customer = get_object_or_404(Customer, user=request.user)
    else:
        uid = request.COOKIES.get('device')
        try:
            customer = Customer.objects.get(uid=uid)
        except:
            customer = Customer(uid=uid)
            if str(customer) == 'None':
                messages.warning(request, 'We use cookies in order to let you order items without an account so please enable cookies(and javascript) or login with your account in order to continue!')
                return redirect('store:index')
            else:
                customer.save()

    orderItems = None

    try:
        orderComplete = Order.objects.filter(customer=customer, complete=True)
        orderItemsComplete = OrderItem.objects.filter(order=orderComplete)
    except:
        orderComplete = None
        orderItemsComplete = None

    try:
        order = Order.objects.get(customer=customer, complete=False)
        orderItems = OrderItem.objects.filter(order=order)

        total = 0
        for item in orderItems:
            total = total + (item.product.price*item.quantity)

        tot = total + round(total/100*10)
        Order.objects.select_for_update().filter(id=order.id).update(total=tot)
    except:
        total = 0
        tot = 0

    # for oi in orderItems:
    #     print(oi.product.qty)

    if request.is_ajax():
        item = request.POST.get('item')
        add = request.POST.get('add')
        data['item'] = item
        data['add'] = add

        item_add = get_object_or_404(OrderItem, id=item)
        qty = item_add.quantity
        qty = qty+int(add)
        OrderItem.objects.select_for_update().filter(id=item).update(quantity=qty)
        if qty == 0:
            item_add.delete()
        order = Order.objects.get(customer=customer, complete=False)
        orderItems = OrderItem.objects.filter(order=order)
        total = 0
        for item in orderItems:
            total = total + (item.product.price*item.quantity)

        tot = total + round(total/100*10)

        Order.objects.select_for_update().filter(id=order.id).update(total=tot)
        order = Order.objects.get(customer=customer, complete=False)

        return JsonResponse(data)

    ctx = {'orderItems': orderItems, 'total': total, 'tot': tot,
           'orderComplete': orderComplete, 'orderItemsComplete': orderItemsComplete}
    return render(request, 'store/cart.html', ctx)


def addtocart(request, item):

    if request.user.is_authenticated:
        customer = get_object_or_404(Customer, user=request.user)
        # product = get_object_or_404(Product, title=item)
        # order = Order.objects.filter(customer=customer, complete=False)
    else:
        uid = request.COOKIES.get('device')
        try:
            customer = Customer.objects.get(uid=uid)
        except:
            customer = Customer(uid=uid)
            if str(customer) == 'None':
                messages.warning(request, 'We use cookies in order to let you order items without an account so please enable cookies(and javascript) or login with your account in order to continue!')
                return redirect('store:index')
            else:
                customer.save()
        

    product = get_object_or_404(Product, title=item)
    order = Order.objects.filter(customer=customer, complete=False)

    if not order:
        order = Order(customer=customer)
        order.save()

    order = Order.objects.get(customer=customer, complete=False)

    try:
        orderItem = OrderItem.objects.get(product=product, order=order)
        qty = orderItem.quantity
        print(qty)
        print('---', orderItem.product.qty)
        if(int(qty) < int(orderItem.product.qty)):
            OrderItem.objects.select_for_update().filter(
                product=product, order=order).update(quantity=qty+1)
        else:
            messages.warning(request, "You can't add anymore of this Item")
            return redirect('store:index')
    except:
        item = OrderItem(product=product, order=order, quantity=1)
        item.save()

    return redirect('store:cart')


def ordercancel(request, orderid):
    order = Order.objects.get(id=orderid)
    orderItems = OrderItem.objects.filter(order=order)
    for items in orderItems:
        if items.product.qty == 0:
            Product.objects.select_for_update().filter(id=items.product.id).update(in_stock=True, qty=items.quantity)
        else:
            p = Product.objects.get(id=items.product.id)
            q = p.qty + items.quantity
            # print(q)
            Product.objects.select_for_update().filter(id=items.product.id).update(qty=q)

    if request.method == 'POST':
        try:
            if not Order.objects.filter(id=orderid):
                raise Http404('404')
            else:
                Order.objects.filter(id=orderid).delete()
                messages.warning(request, 'Your order was canceled!')
        except:
            raise Http404('404')
       
    return redirect('store:cart')


def checkout(request):
    form = CreateShippingAddress()

    errors = ''
    if request.user.is_authenticated:
        customer = get_object_or_404(Customer, user=request.user)
    else:
        uid = request.COOKIES.get('device')
        customer = Customer.objects.get(uid=uid)

    try:
        order = Order.objects.get(customer=customer, complete=False)
        if len(order.orderitem_set.all()) == 0:
            messages.error(request, 'Add Items to your cart first')
            return redirect('store:index')
    except:
        messages.error(request, 'Add Items to your cart first')
        return redirect('store:index')

    
        # print('--', items.quantity)
        # print(items.product.qty)
            
    if request.method == 'POST':
        form = CreateShippingAddress(request.POST)
        if form.is_valid():
            address1 = request.POST.get('address')
            address2 = request.POST.get('address2')
            state = request.POST.get('state')
            city = request.POST.get('city')
            address = ShippingAddress.objects.filter(
                address=address1, address2=address2, city=city, state=state)
            if len(address) > 0:
                address = address[0]
            else:
                form.save()
                address = ShippingAddress.objects.get(address=address1, address2=address2, city=city, state=state)

            transaction_id = int(
                round(datetime.datetime.timestamp(datetime.datetime.now()), 0))
            some_date = datetime.date.today()
            three_months = datetime.timedelta(2*365/12)
            eta = some_date + three_months
            

store/templates/store/cart.html
{% extends "index/base.html" %}
{% block title %}cart{% endblock %} 
{% load mathfilters %}
{% load static %}

{% block content %}
<div class="px-4 px-lg-0">
    <!-- https://bootstrapious.com/p/bootstrap-shopping-cart -->
  <!-- For demo purpose -->
  <!-- <div class="container text-white py-5 text-center">
    <h1 class="display-4">Bootstrap 4 shopping cart</h1>
    <p class="lead mb-0">Build a fully structred shopping cart page using Bootstrap 4. </p>
    <p class="lead">Snippet by <a href="https://bootstrapious.com/snippets" class="text-white font-italic">
            <u>Bootstrapious</u></a>
    </p>
  </div> -->
  <!-- End -->


  <div class="pb-5 mt-4">
    <div class="container">
      {% for message in messages %}
        <div {% if message.tags != 'error'%} class="mt-4 alert alert-{{ message.tags }} 
      {% elif message.tags == 'error' %}
        class=" mt-4 alert alert-danger {% endif %} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
      <div class="row">
        <div class="col-lg-12 p-md-5 pb-0 bg-white rounded shadow-sm mb-5 p-sm-1 pt-sm-5">

          <!-- Shopping cart table -->
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Product</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Price</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Quantity</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Total</div>
                  </th>
                </tr>
              </thead>
              <tbody>
              {% for order in orderItems %}
                  <tr>
                    <th scope="row" class="border-0 col-8">
                      <div class="p-2 ">
                        <img src="{% static order.product.image %}" alt="" width="70" class="img-fluid rounded shadow-sm">
                        <div class="ml-3 d-inline-block align-middle w-75">
                          <h5 class="mb-0 w-75"> <a href="#" class="text-dark d-inline-block align-middle">{{order.product}}</a></h5><span class="text-muted font-weight-normal font-italic d-block">Category: {{order.product.category}}</span>
                        </div>
                      </div>
                    </th>
                    <div class="col">
                      <td class="border-0 align-middle"><strong>$ <span class="ppp">{{order.product.price|floatformat:2}}</span></strong></td>
                    <td class="border-0 align-middle">
                      <div >
                      <form action="" method='POST' class="qty">
                        {% csrf_token %}
                        <input type="text" name='order' value={{ order.id }} hidden>
                        <button type='submit' class='btn' name='add' value=-1><i class="fas fa-sort-down"></i></button>
                        <span class='qtyrel'>{{order.quantity}}</span> /<strong class="maxqty">{{ order.product.qty }}</strong>
                        <!-- <input type="number" min=0 value="{{order.quantity}}" disabled> -->
                        <button type='submit' class='btn' name='add' value=+1><i class="fas fa-sort-up"></i></button>
                      </form>
                    </td>
                    <td class="border-0 align-middle">$ <span class="total-o">{{order.getTotal|floatformat:2}}</span></td>
                    </div>
                   
                    </div>
                  </tr>
              {% endfor %}
                
              </tbody>
            </table>
          </div>
          
          <a href={% url 'store:index' %} class="btn btn-outline-secondary my-5">Continue shopping &#8594;</a>

          <!-- End -->
        </div>
      </div>

      <div class="row py-5 p-4 bg-white rounded shadow-sm">
        <div class="col-lg-6">
          
          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Instructions for seller</div>
          <div class="p-4">
            <p class="font-italic mb-4">If you have some information for the seller you can leave them in the box below</p>
            <textarea name="" cols="30" rows="2" class="form-control"></textarea>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Order summary </div>
          <div class="p-4">
            <p class="font-italic mb-4">Shipping and additional costs are calculated based on values you have entered.</p>
            <p class="text-black-50">(Make sure to refresh the page for the total to be calculated)</p>
            <ul class="list-unstyled mb-4">
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Order Subtotal </strong><strong> $<span id="totalt">{{total|floatformat:2}}</span></strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Shipping and handling</strong><strong>$ <span id="shipment">{% widthratio total 100 10 %}</span> </strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Tax</strong><strong>$0.00</strong></li>
              <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total</strong>
                <h5 class="font-weight-bold">$<span id="total-final">{{tot|floatformat:2}}</span></h5>
              </li>
            </ul><a href={% url 'store:checkout' %} class="btn btn-dark rounded-pill py-2 btn-block">Procceed to checkout</a>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


{% if orderComplete %}
  <div class="container mt-3">
  <h4>Orders awaiting shipment:</h4>
  </div>
    {% for order in orderComplete %}
      <div class="container mt-3">
        <h5>Order: {{ forloop.counter }}</h5>
        <div class="col-lg-12 p-5 py-2 bg-white rounded shadow-sm mb-5">
        
        <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="border-0 bg-light">
                    <div class="p-2 px-3 text-uppercase">Product</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Price</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Quantity</div>
                  </th>
                  <th scope="col" class="border-0 bg-light">
                    <div class="py-2 text-uppercase">Total</div>
                  </th>
                </tr>
              </thead>
              <tbody>
              
              {% for order in order.orderitem_set.all %}
                  <tr>
                    <th scope="row" class="border-0">
                      <div class="p-2">
                        <img src="{% static order.product.image %}" alt="" width="70" class="img-fluid rounded shadow-sm">
                        <div class="ml-3 d-inline-block align-middle">
                          <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">{{order.product}}</a></h5><span class="text-muted font-weight-normal font-italic d-block">Category: {{order.product.category}}</span>
                        </div>
                      </div>
                    </th>
                    <td class="border-0 align-middle"><strong>$ <span class="ppp">{{order.product.price|floatformat:2}}</span></strong></td>
                    <td class="border-0 align-middle"><strong> <span class="ppp">{{order.quantity}}</span></strong></td>
                    <td class="border-0 align-middle">$ <span class="total-o">{{order.getTotal|floatformat:2}}</span></td>
                   
                    </div>
                  </tr>
              {% endfor %}
                
              </tbody>
            </table>
          </div>
          <div class="container my-4">
            <div class="row">
              <div class="col-sm">
                <form action={% url 'store:ordercancel' order.id %} method='POST'>
                  {% csrf_token %}
                  <button type='submit' class="btn btn-danger w-50">Cancel order</button>
                </form>
              </div>
              <div class="col-sm d-flex justify-content-center">
                Transaction id: {{ order.transaction_id }}
              </div>
              <div class="col-sm d-flex justify-content-end" >
                Order Total: ${{ order.totalAfterCoupon|floatformat:2}}
              </div>
            </div>
          </div>
        
        </div>
      </div>
    {% endfor %}
  {% endif %}
  


<script>
  const qty = document.getElementsByClassName('qty')
  var totalo = document.getElementsByClassName('total-o')
  var ppp = document.getElementsByClassName('ppp')
  var totalt = document.getElementById('totalt') 
  var shipment = document.getElementById('shipment') 
  var totalFinal = document.getElementById('total-final') 

  //console.log(parseFloat(totalt.textContent), parseInt(shipment.textContent), parseFloat(totalFinal.textContent))

  sh = (parseInt(totalt.textContent)/100*10).toFixed(0)
  tfinal = (parseFloat(totalt.textContent) + parseInt(sh))


  const url = ""

  for(var i = 0; i < qty.length; i++){
    //console.log(qty[i].children[3].valueAsNumber)
    let item = qty[i].children[1]
    let quant = qty[i].children[3]
    let maxQuant =  qty[i].children[4]
    let a = qty[i].children[5]
    let csrf = qty[i].children[0]
    let f = qty[i];

    f.addEventListener('submit', fun=>{
      fun.preventDefault();
    })

    let tot = totalo[i]
    let price = ppp[i]

    a.addEventListener('click', e=>{
      if(parseInt(quant.textContent) < parseInt(maxQuant.textContent)) {
      
        quant.textContent = parseInt(quant.textContent) + 1
        tot.textContent = (parseInt(quant.textContent)*parseFloat(price.textContent)).toFixed(2)
        totalt.textContent = (parseFloat(price.textContent) + parseFloat(totalt.textContent)).toFixed(2)
        sh = (parseInt(totalt.textContent)/100*10).toFixed(0)
        shipment.textContent = parseInt(sh)
        tfinal = (parseFloat(totalt.textContent) + parseInt(sh))
        totalFinal.textContent = tfinal.toFixed(2)

        const fd = new FormData()
        fd.append('item', item.value)
        fd.append('csrfmiddlewaretoken', csrf.value)
        fd.append('add', a.value)
        //console.log(item.value, a.value)
        $.ajax({
          type: 'POST',
          url: url,
          data: fd,
          cache: false,
          processData: false,
          contentType: false,
          success: function (success){
              console.log(success)
          },
          error: function(error) {
              console.log(error)
          }
          })
      }else {
        alert('You have reached The max ammount in stock')
      }
     
    })

    let r = qty[i].children[2]
    r.addEventListener('click', e=>{
      quant.textContent = parseInt(quant.textContent) - 1
      tot.textContent = (parseInt(quant.textContent)*parseFloat(price.textContent)).toFixed(2)
      totalt.textContent = (parseFloat(totalt.textContent) - parseFloat(price.textContent)).toFixed(2)
      sh = (parseInt(totalt.textContent)/100*10).toFixed(0)
      shipment.textContent = parseInt(sh)
      tfinal = (parseFloat(totalt.textContent) + parseInt(sh))
      totalFinal.textContent = tfinal.toFixed(2)

      const fd = new FormData()
      fd.append('item', item.value)
      fd.append('add', r.value)
      fd.append('csrfmiddlewaretoken', csrf.value)
      //console.log(item.value, r.value)
      $.ajax({
        type: 'POST',
        url: url,
        data: fd,
        cache: false,
        processData: false,
        contentType: false,
        success: function (success){
            console.log(success,)
        },
        error: function(error) {
            console.log(error)
        },
        })
        if(parseInt(quant.textContent) <= 0) {
          setTimeout(() => {  location.reload();  }, 100);
        }
    })
  }

  // {% comment %} const items = document.getElementsByName('order')
  // const add = document.getElementsByName('add')
  // const csrf = document.getElementsByName('csrfmiddlewaretoken')
  // const form = document.getElementsByClassName('form')
  // const url = ""

  // //console.log(form)

  // for(var i=0; i < form.length; i++){
  //   let f = form[i];
  //   f.addEventListener('submit', e=>{
  //     e.preventDefault()
  //     const fd = new FormData()
  //     fd.append('csrfmiddlewaretoken', f[0].value)
  //     fd.append('items', f[1].value)
  //     fd.append('add', f[2].value)
  //     console.log(f[2].value, f[3].value)

  //   })
  // } {% endcomment %}
</script>
{% endblock %} 

store/templates/store/trackorder.html
{% extends "index/base.html" %}
{% block title %}Track Your order{% endblock %} 
{% load mathfilters %}

{% block content %}


<div class="container">
{% for message in messages %}
  <p{% if message.tags != 'error'%} class="mt-4 alert alert-{{ message.tags }}"
  {% elif message.tags == 'error' %}
   class="mt-4 alert alert-danger"
  {% endif %}>{{ message }}</p>
{% endfor %}
</div>
<form class="d-flex container mt-5 tex-center" method='POST' action={% url 'store:trackorderred' %}>
{% csrf_token %}
<div class="input-group mb-3">
  <span class="input-group-text bg-info" id="basic-addon2" >Track your order:</span>
  <input type="text" class="form-control" placeholder="Your transaction id" id="basic-url" aria-describedby="basic-addon3" name='order_track'>
  <button class="btn btn-outline-success" type="submit">Search</button>
</div>
</form>



{% endblock %} 