index/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    path('account/<slug:user>', views.userAccount, name="userAccount"),
    path('account/<slug:user>/password_forgot', views.forgotPassword, name="forgotPassword"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('store/', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'store'

urlpatterns = [
    path('test/', views.test, name="test"),
    path('', views.index, name="index"),
    path('cart/', views.cart, name="cart"),
    path('<slug:orderid>/ordercancel/', views.ordercancel, name="ordercancel"),
    path('checkout/', views.checkout, name="checkout"),
    path('addtocart/<item>/', views.addtocart, name="addtocart"),
    path('trackorderred/', views.trackorderred, name="trackorderred"),
    path('trackorder/', views.track_order, name="track_order"),
    path('trackorder/<slug:order_track>', views.trackorder, name="trackorder"),
    path('apply_coupon/', views.apply_coupon, name="apply_coupon"),
    path('remove_coupon/', views.remove_coupon, name="remove_coupon"),
    path('add_product/', views.addProduct, name="addProduct"),
    path('rate_product/', views.rate_product, name="rate_product"),
    path('product/<int:product_id>', views.viewProduct, name="viewProduct"),
    path('api/products', views.productsApi, name='productApi'), 
    path('api/', views.api, name='api'), 
    path('api/products/<str:pk>', views.singleProductApi, name='singleProductApi'), 
]

index/templates/index/account.html
{% extends "index/base.html" %}
{% block title %}Account{% endblock %} 

{% block content %}
<div class="container h-100 mt-5">

	{% comment %} {{ request.META.HTTP_REFERER }} {% endcomment %}
	<div class="d-flex justify-content-center h-100">
		<div class="user_card reg">
			<div class="d-flex justify-content-center">
				<h3 id="form-title">REGISTER ACCOUNT</h3>
			</div>
			<div class="d-flex justify-content-center form_container">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="input-group mb-3">
                        
						<span class="input-group-text"><i class="fas fa-user"></i></span>
						{{ form.first_name }}

					</div>
					<div class="input-group mb-3">

						<span class="input-group-text"><i class="fas fa-user"></i></span>

						{{ form.last_name }}
					</div>
					<div class="input-group mb-3">

						<span class="input-group-text"><i class="fas fa-user"></i></span>

						{{ form.username }}
					</div>

					<div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>

						{{ form.email }}
					</div>

					<div class="d-flex justify-content-center mt-3 login_container">
						<input class="btn login_btn" type="submit" value="Save Changes">
					</div>
                    <div class="d-flex justify-content-center links resp-p">
                        <a href={% url 'index:forgotPassword' request.user%} class="ml-2">Change Password</a>
                        </div>
				</form>
			</div>
		    {% for e in err %}
			<span class="messages">{{ e }}</span>
			{% endfor %} 



			
		</div>
	</div>
</div>
<script>
	var form_fields = document.getElementsByTagName('input')
	form_fields[1].placeholder = 'First Name..';
	form_fields[2].placeholder = 'Last Name..';
	form_fields[3].placeholder = 'Username..';
	form_fields[4].placeholder = 'Email..';


	for (var field in form_fields) {
		form_fields[field].className += ' form-control'
	}
</script>
{% comment %} <form action="" method='POST'>
{% csrf_token %}
{{form}}
<input type="submit" name="" id="">
</form> {% endcomment %}
{% endblock %}

index/templates/index/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href={% static '/css/main.css' %}>
    <link rel="stylesheet" href={% static '/css/bootstrap.css' %}>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
      integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu"
      crossorigin="anonymous"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <script>

      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
      }
      function uuidv4() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
          var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
          return v.toString(16);
        });
      }

      let device = getCookie('device')

      if(device == null || device == undefined){
        expiry = new Date();   
        expiry.setTime(Date.now()+(4000*60*1000)); 
        device = uuidv4()
        document.cookie = 'device=' + device + ";domain=;path=/;expires=" + expiry.toGMTString() + "; Secure"; 
      } else{
        document.cookie = 'device=' + device + ";domain=;path=/"  + "; Secure"; 
      }



    </script>

    <style>

    /*********************************************
    			Call Bootstrap
*********************************************/

@import url("bootstrap/bootstrap.min.css");
@import url("bootstrap-override.css");
@import url("//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css");

/*********************************************
        		Theme Elements
*********************************************/

.gold{
	color: #FFBF00;
}

/*********************************************
					PRODUCTS
*********************************************/

.product2{
	border: 1px solid #dddddd;
	height: 321px;
}

.product>img{
	max-width: 230px;
}

.product-rating{
	font-size: 20px;
	margin-bottom: 25px;
}

.product-title{
	font-size: 20px;
}

.product-desc{
	font-size: 14px;
}

.product-price{
	font-size: 22px;
}

.product-stock{
	color: #74DF00;
	font-size: 20px;
	margin-top: 10px;
}

.product-info{
		margin-top: 50px;
}

.my-btn {
  border:0;
  background-color: inherit !important;
}

.checked {
  color: orange;
}

/*********************************************
					VIEW
*********************************************/

.content-wrapper2  {
	max-width: 1140px;
	background: #fff;
	margin: 0 auto;
	margin-top: 25px;
	margin-bottom: 10px;
	border: 0px;
	border-radius: 0px;
}

.container-fluid2 {
	max-width: 1140px;
	margin: 0 auto;
}

.view-wrapper2 {
	float: right;
	max-width: 70%;
	margin-top: 25px;
}

.container2  {
	padding-left: 0px;
	padding-right: 0px;
	max-width: 100%;
} 

/*********************************************
				ITEM 
*********************************************/

.service1-items {
	padding: 0px 0 0px 0;
	float: left;
	position: relative;
	overflow: hidden;
	max-width: 100%;
	height: 321px;
	width: 130px;
}

.service1-item {
	height: 107px;
	width: 120px;
	display: block;
	float: left;
	position: relative;
	padding-right: 20px;
	border-right: 1px solid #DDD;
	border-top: 1px solid #DDD;
	border-bottom: 1px solid #DDD;
}

.service1-item > img {
	max-height: 110px;
	max-width: 110px;
	opacity: 0.6;
	transition: all .2s ease-in;
	-o-transition: all .2s ease-in;
	-moz-transition: all .2s ease-in;
	-webkit-transition: all .2s ease-in;
}

.service1-item > img:hover {
	cursor: pointer;
	opacity: 1;
}

.service-image-left {
	padding-right: 50px;
}

.service-image-right {
	padding-left: 50px;
}

.service-image-left > center > img,.service-image-right > center > img{
	max-height: 155px;
}

    
      input[type=number] {
        text-align: center;
        border: none;
        border-top: 1px solid #ddd;
        border-bottom: 1px solid #ddd;
        margin: 0px;
        width: 40px;
        height: 40px;
      }

      input[type=number] { 
          -moz-appearance: textfield;
          appearance: textfield;
          margin: 0; 
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href={% url 'store:index' %}>Store</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={% url 'store:track_order' %}>Track your order  </a>
            </li>
            
            {% ifequal request.user.groups.all.0.name 'Sellers' %}
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'store:addProduct' %}">Add a product</a>
              </li>
            {% endifequal %}
            {% comment %} <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li> {% endcomment %}
            
          </ul>
         
          
          <a href={% url 'store:cart' %} class="btn btn-outline m-2 mt-0 mb-0" type="submit"><i class="fas fa-shopping-cart text-white"></i><span class="badge cart rounded-pill m-1 border border-secondary">
            {% if orderItems %}
            {{ orderItems.count }}
            {% else %}
             0 
            {% endif %}
          </span></a>
          {% if request.user.is_authenticated %}
          <a href={% url 'index:userAccount' request.user.username %} class="btn btn-outline-primary m-2 mt-0 mb-0" type="submit">
            {{ request.user.username }}
          </a>
          <a href={% url 'index:logout' %} class="btn btn-outline-danger m-2 mt-0 mb-0" type="submit">
            Logout
          </a>
          {% else %}
          <div class="d-flex">
            <a href={% url 'index:login' %} class="btn btn-outline-info m-2 mt-0 mb-0" type="submit">
              Login
            </a>
            <!-- <a href={% url 'index:register' %} class="btn btn-outline-success" type="submit">
              Register
            </a> -->
          </div>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <!-- JavaScript Bundle with Popper -->

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

index/templates/index/landing.html
{% extends "index/base.html" %}
{% block title %}Landing{% endblock %} 

{% block content %}
<h1>lanfing Page</h1>
{% endblock %}

index/templates/index/login.html
{% extends "index/base.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container h-100 mt-5">
  {% comment %} {{ request.META.HTTP_REFERER }} {% endcomment %}
  <div class="d-flex justify-content-center h-100">
    <div class="user_card reg">
      <div class="d-flex justify-content-center">
        <h3 id="form-title">LOGIN</h3>
      </div>
      <div class="d-flex justify-content-center form_container">
        <form method="POST" action="">
          {% csrf_token %}
          <div class="input-group mb-3">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
            <input
              type="text"
              name="username"
              placeholder="Username..."
              class="form-control"
            />
          </div>
          <div class="input-group mb-2">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
            <input
              type="password"
              name="password"
              placeholder="Password..."
              class="form-control"
            />
          </div>

          <div class="d-flex justify-content-center mt-3 login_container">
            <input class="btn login_btn" type="submit" value="Login" />
          </div>
          <input type="hidden" name="next" value="{{ request.GET.next }}" />
        </form>
      </div>
      {% for message in messages %}
      <p id="messages">{{ message }}</p>
      {% endfor %}

      <div class="mt-4">
        <div class="d-flex justify-content-center links resp-p">
          Don't have an account?
          <a href="{% url 'index:register' %}" class="ml-2"> Sign Up</a>
        </div>
        <div class="d-flex justify-content-center links resp-p">
          Forgot Password?
          <a href="" class="ml-2">Reset Password</a>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var form_fields = document.getElementsByTagName("input");
  form_fields[1].placeholder = "First Name..";
  form_fields[2].placeholder = "Last Name..";
  form_fields[3].placeholder = "Username..";
  form_fields[4].placeholder = "Email..";
  form_fields[5].placeholder = "Enter password...";
  form_fields[6].placeholder = "Re-enter Password...";

  for (var field in form_fields) {
    form_fields[field].className += " form-control";
  }
</script>
{% endblock %}

index/templates/index/passwordforgot.html
{% extends "index/base.html" %} 
{% block title %}{% endblock %}
{% block content %}
<div class="container h-100 mt-5">

	{% comment %} {{ request.META.HTTP_REFERER }} {% endcomment %}
	<div class="d-flex justify-content-center h-100">
		<div class="user_card reg">
			<div class="d-flex justify-content-center">
				<h3 id="form-title">REGISTER ACCOUNT</h3>
			</div>
			<div class="d-flex justify-content-center form_container">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-key"></i></span>

						{{ form.old_password }}
					</div>
                    <div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-key"></i></span>

						{{ form.new_password1 }}
					</div>
                    <div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-key"></i></span>

						{{ form.new_password2 }}
					</div>
					

					<div class="d-flex justify-content-center mt-3 login_container">
						<input class="btn login_btn" type="submit" value="Update password">
					</div>
				</form>
			</div>
		  {% for e in err %}
			<span class="messages">{{ e }}</span>
			{% endfor %} 


		
		</div>
	</div>
</div>
<script>
	var form_fields = document.getElementsByTagName('input')
	form_fields[1].placeholder = 'Old password';
	form_fields[2].placeholder = 'New Password';
	form_fields[3].placeholder = 'Repeat password';

	for (var field in form_fields) {
		form_fields[field].className += ' form-control'
	}
</script>
{% endblock %} 

index/templates/index/register.html
{% extends "index/base.html" %} 
{% block title %}{% endblock %}
{% block content %}
<div class="container h-100 mt-5">

	{% comment %} {{ request.META.HTTP_REFERER }} {% endcomment %}
	<div class="d-flex justify-content-center h-100">
		<div class="user_card reg">
			<div class="d-flex justify-content-center">
				<h3 id="form-title">REGISTER ACCOUNT</h3>
			</div>
			<div class="d-flex justify-content-center form_container">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="input-group mb-3">

						<span class="input-group-text"><i class="fas fa-user"></i></span>

						{{ form.first_name }}

					</div>
					<div class="input-group mb-3">

						<span class="input-group-text"><i class="fas fa-user"></i></span>

						{{ form.last_name }}
					</div>
					<div class="input-group mb-3">

						<span class="input-group-text"><i class="fas fa-user"></i></span>

						{{ form.username }}
					</div>

					<div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>

						{{ form.email }}
					</div>
					<div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-key"></i></span>

						{{ form.password1 }}
					</div>
					<div class="input-group mb-2">

						<span class="input-group-text"><i class="fas fa-key"></i></span>

						{{ form.password2 }}
					</div>

					<div class="d-flex justify-content-center mt-3 login_container">
						<input class="btn login_btn" type="submit" value="Register Account">
					</div>
				</form>
			</div>
		  {% for e in err %}
			<span class="messages">{{ e }}</span>
			{% endfor %} 


			<div class="mt-4">
				<div class="d-flex justify-content-center links">

					Already have an account? <a href={% url 'index:login' %} class="ml-2">Login</a>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	var form_fields = document.getElementsByTagName('input')
	form_fields[1].placeholder = 'First Name..';
	form_fields[2].placeholder = 'Last Name..';
	form_fields[3].placeholder = 'Username..';
	form_fields[4].placeholder = 'Email..';
	form_fields[5].placeholder = 'Enter password...';
	form_fields[6].placeholder = 'Re-enter Password...';


	for (var field in form_fields) {
		form_fields[field].className += ' form-control'
	}
</script>
{% endblock %} 